CREATE TABLE users(id INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(20), age INT);

INSERT INTO users(NAME, age) VALUES('孤傲苍狼', 27);
INSERT INTO users(NAME, age) VALUES('白虎神皇', 27);


CREATE TABLE t_user(id INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(20), age INT);
INSERT INTO t_user(NAME, age) VALUES('孤傲苍狼', 27);
INSERT INTO t_user(NAME, age) VALUES('白虎神皇', 27);