CREATE TABLE users(id INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(20), age INT);

INSERT INTO users(NAME, age) VALUES('孤傲苍狼', 27);
INSERT INTO users(NAME, age) VALUES('白虎神皇', 27);

DROP TABLE  IF EXISTS t_user;
CREATE TABLE IF NOT EXISTS t_user(
  id INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  age INT DEFAULT 0,
  gender SMALLINT DEFAULT NULL
);
INSERT INTO t_user(NAME, age, gender) VALUES('小明', 27, 1);
INSERT INTO t_user(NAME, age, gender) VALUES('小红', 27, 0);